---
- name: use namegen api to generate random names
  register: ar_random_names
  with_sequence: count="{{ _count }}"
  ansible.builtin.uri:
    url: "http://{{ ar_get_route_result.resources[0].spec.host }}/api/random_name"
    method: GET
    headers:
      Accept: application/json

- name: use namegen api to save random name
  loop: "{{ ar_random_names.results }}"
  loop_control:
    label: "{{ item.json }}"
  ansible.builtin.uri:
    url: "http://{{ ar_get_route_result.resources[0].spec.host }}/api/names"
    method: POST
    headers:
      Content-Type: application/json
    body_format: json
    body: "{{ item.json }}"
...
