---
- name: wait 5 seconds
  ansible.builtin.set_fact:
    __: "{{ lookup('ansible.builtin.pipe', 'sleep 5') }}"

- name: wait for deployments to be ready
  register: ar_deployment_result
  loop:
    - kind: StatefulSet
      name: mongodb
    - kind: Deployment
      name: namegen
  until:
    - ar_deployment_result.resources                      # just in case
    - ar_deployment_result.resources[0].status is defined
    - ar_deployment_result.resources[0].status.readyReplicas is defined
    - ar_deployment_result.resources[0].status.readyReplicas == ar_deployment_result.resources[0].spec.replicas
  delay: 3
  retries: 18
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
    namespace: "{{ ar_app_namespace }}"
    kubeconfig: "{{ kubeconfig_file }}"
...
