---
- name: Set namespace name
  ansible.builtin.set_fact:
    ar_app_namespace: "{{ app_namespace_prefix }}{{ lookup('password', '/dev/null chars=ascii_letters, length=5') | lower }}"

- name: Block with always
  block:
    - name: Create namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ ar_app_namespace }}"
        state: present
        # kubeconfig: "{{ kubeconfig_file }}"

    - name: Test stateful app
      ansible.builtin.import_tasks: stateful-app/main.yaml

    - name: Test stateless app
      ansible.builtin.import_tasks: stateless-with-rbac-app/main.yaml

  always:
    - name: Delete namespace
      when: delete_resources | bool
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ ar_app_namespace }}"
        state: absent
        wait: true
        # kubeconfig: "{{ kubeconfig_file }}"
...
