---
- name: initialize variables
  ansible.builtin.set_fact:
    cr_master_nodes: []
    cr_worker_nodes: []
    cr_infra_nodes: []

- name: get nodes
  register: cr_get_node_result
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    kubeconfig: "{{ kubeconfig_file }}"

- name: parse nodes
  loop: "{{ cr_get_node_result.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"
  vars:
    cr_node_labels: "{{ item.metadata.labels.keys() | list }}"
  ansible.builtin.set_fact:
    cr_master_nodes: "{{ cr_master_nodes + ([item.metadata.name] if master_node_label in cr_node_labels else []) }}"
    cr_worker_nodes: "{{ cr_worker_nodes + ([item.metadata.name] if worker_node_label in cr_node_labels else []) }}"
    cr_infra_nodes: "{{ cr_infra_nodes + ([item.metadata.name] if infra_node_label in cr_node_labels else []) }}"

- name: report if no infra nodes defined
  when: (cr_infra_nodes | length) == 0
  vars:
    _new_result: "no infra nodes defined"
  ansible.builtin.include_tasks: store-result.yaml

- name: report if incorrect infra nodes count
  when: (cr_infra_nodes | length) != infra_nodes
  vars:
    _new_result: "infra nodes count {{ cr_infra_nodes | length }} does not match spec: {{ infra_nodes }}"
  ansible.builtin.include_tasks: store-result.yaml

- name: report if infra nodes also labeled as worker nodes
  when: (cr_infra_nodes | intersect(cr_worker_nodes) | length) > 0
  vars:
    _new_result: "the following infra nodes are also labeled as worker nodes: {{ cr_infra_nodes | intersect(cr_worker_nodes) | join(', ') }}"
  ansible.builtin.include_tasks: store-result.yaml

- name: only if there are infra nodes
  when: (cr_infra_nodes | length) > 0
  block:
    - name: get pods of interest
      loop:
        - openshift-ingress
        - openshift-image-registry
        - openshift-monitoring
        - openshift-user-workload-monitoring
        - openshift-logging
        - rhacs-operator
        - "{{ rhacs_namespace }}"
        - openshift-gitops-operator
        - openshift-gitops
        - openshift-cnv
      register: cr_get_pods_result
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ item }}"
        kubeconfig: "{{ kubeconfig_file }}"

    - name: parse pods
      vars:
        _all_pod: "{{ cr_get_pods_result.results | map(attribute='resources') | flatten }}"
        _master_nodes: "{{ cr_master_nodes }}"
        _infra_nodes: "{{ cr_infra_nodes }}"
      ansible.builtin.set_fact:
        bad_placement_pods: "{{ lookup('ansible.builtin.template', 'infra-pods-not-on-infra-nodes.j2') | from_yaml }}"

    - name: report if pods not on infra nodes
      loop:
        - name: openshift-ingress
          var:  "{{ bad_placement_pods.ingress }}"
        - name: openshift-image-registry
          var:  "{{ bad_placement_pods.registry }}"
        - name: openshift-monitoring
          var:  "{{ bad_placement_pods.monitoring }}"
        - name: openshift-user-workload-monitoring
          var:  "{{ bad_placement_pods.user_monitoring }}"
        - name: openshift-logging
          var:  "{{ bad_placement_pods.logging }}"
        - name: rhacs
          var:  "{{ bad_placement_pods.rhacs }}"
        - name: openshift-gitops
          var:  "{{ bad_placement_pods.gitops }}"
        - name: openshift-cnv
          var:  "{{ bad_placement_pods.cnv }}"
      loop_control:
        label: "{{ item.name }}"
      when: (item.var | length) > 0
      vars:
        _new_result: "the following {{ item.name }} pods not on infra nodes: {{ item.var | join(', ') }}"
      ansible.builtin.include_tasks: store-result.yaml
...
