# ---
- name: get image registry CustomResourceDefinition
  register: cr_ir_crd_result
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: configs.imageregistry.operator.openshift.io
    kubeconfig: "{{ kubeconfig_file }}"

- name: get image registry config
  register: cr_ir_config_result
  kubernetes.core.k8s_info:
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
    name: cluster
    kubeconfig: "{{ kubeconfig_file }}"

- name: parse image registry crd
  ansible.builtin.set_fact:
    # get the storage types supported by the operator expect emptyDir
    cr_storage_types: "{{ (cr_ir_crd_result.resources[0].spec.versions | selectattr('name', '==', 'v1') |
                           map(attribute='schema.openAPIV3Schema.properties.spec.properties.storage.properties'))[0].keys() |
                          difference(['emptyDir', 'managementState']) }}"
    cr_registry_storage: "{{ cr_ir_config_result.resources[0].spec.storage.keys() | difference(['managementState']) }}"

- name: report if openshift image registry is using emptyDir storage
  when:
    - cr_ir_config_result.resources[0].spec.managementState == "Managed"
    - (cr_registry_storage | difference(cr_storage_types) | length) != 0
  vars:
    _new_result: "openshift image registry is using emptyDir storage"
  ansible.builtin.include_tasks: store-result.yaml
...
