---
- name: initialize variables
  ansible.builtin.set_fact:
    cr_verification_results: []
    cr_all_completed: false
    cr_working_namespace: "{{ working_namespace_prefix }}{{ lookup('password', '/dev/null chars=ascii_letters, length=5') | lower }}"

- name: block with yaml
  block:
    # for oc debug
    - name: create working namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ cr_working_namespace }}"
        state: present
        kubeconfig: "{{ kubeconfig_file }}"

    - name: oAuth server metadata
      ansible.builtin.import_tasks: oauth-server-metadata.yaml

    - name: ClusterVersion
      ansible.builtin.import_tasks: cluster-version.yaml

    - name: ClusterOperators
      ansible.builtin.import_tasks: cluster-operators.yaml

    - name: MachineConfigPool
      ansible.builtin.import_tasks: machine-config-pools.yaml

    - name: machine
      ansible.builtin.import_tasks: machines.yaml

    - name: nodes
      ansible.builtin.import_tasks: nodes.yaml          # this task list must run after machines.yaml

    - name: CertificateSigningRequest
      ansible.builtin.import_tasks: csr.yaml

    - name: wildcard dns and wildcard certificate
      ansible.builtin.import_tasks: wildcard-dns.yaml

    - name: CoreDNS
      ansible.builtin.import_tasks: core-dns.yaml

    - name: ntp verification
      ansible.builtin.import_tasks: ntp.yaml

    - name: kubeadmin user
      ansible.builtin.import_tasks: kubeadmin.yaml

    - name: oAuth
      ansible.builtin.import_tasks: oauth.yaml

    - name: motd
      ansible.builtin.import_tasks: cli-motd.yaml

    - name: etcd
      ansible.builtin.import_tasks: etcd.yaml

    - name: tlsSecurityProfile
      ansible.builtin.include_tasks: tls-security-profile.yaml

    - name: audit profile
      ansible.builtin.import_tasks: audit.yaml

    - name: project self provisioner
      ansible.builtin.import_tasks: project-self-provisioner.yaml

    - name: project request template
      ansible.builtin.import_tasks: project-template.yaml

    - name: StoregeClass
      ansible.builtin.import_tasks: storage-classes.yaml

    - name: OperatorHub
      ansible.builtin.import_tasks: operator-hub.yaml

    - name: monitoring stack
      ansible.builtin.import_tasks: monitoring.yaml

    - name: monitoring stack - AlertManager
      ansible.builtin.import_tasks: alerting.yaml

    - name: logging stack
      ansible.builtin.import_tasks: logging.yaml

    - name: image controller config
      ansible.builtin.import_tasks: image-controller-config.yaml

    - name: openshift image registry
      ansible.builtin.import_tasks: internal-image-registry.yaml

    - name: pods
      ansible.builtin.import_tasks: pods.yaml

    - name: all validations completed, playbook did not crash
      ansible.builtin.set_fact:
        cr_all_completed: true

  always:   # always clean up and display the report even if playbook did not run to completion
    - name: delete working namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ cr_working_namespace }}"
        state: absent
        kubeconfig: "{{ kubeconfig_file }}"

    - name: display validation report
      ansible.builtin.debug:
        msg:
          status: "{{ lookup('ansible.builtin.template', 'validation-status.j2') | trim }}"
          message: "{{ 'validation did not complete.' if not cr_all_completed else omit }}"
          findings: "{{ cr_verification_results if (cr_verification_results | length) != 0 else omit }}"
...
