---
- name: initialize variables
  ansible.builtin.set_fact:
    cr_default_sc: []

- name: get storage classes
  register: cr_get_sc_result
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    kubeconfig: "{{ kubeconfig_file }}"

- name: parse storage classes result
  loop: "{{ cr_get_sc_result.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"
  when:
    - "'storageclass.kubernetes.io/is-default-class' in item.metadata.annotations"
    - item.metadata.annotations['storageclass.kubernetes.io/is-default-class'] == "true"
  ansible.builtin.set_fact:
    cr_default_sc: "{{ cr_default_sc | default([]) + [item.metadata.name] }}"

- name: report if more than one default storage classes
  when: cr_default_sc | length > 1
  vars:
    _new_result: "more than one default storage classes configured: {{ cr_default_sc | join(', ') }}"
  ansible.builtin.include_tasks: store-result.yaml

- name: report if no default storage classes
  when: cr_default_sc | length == 0
  vars:
    _new_result: "no default storage class configured"
  ansible.builtin.include_tasks: store-result.yaml

- name: report if default storage class is as specified
  when:
    - cr_default_sc | length == 1
    - default_storage_class not in cr_default_sc
  vars:
    _new_result: "default storage class is as specified"
  ansible.builtin.include_tasks: store-result.yaml
...
