---
control_node_labels:
  - node-role.kubernetes.io/master
  - node-role.kubernetes.io/control-plane
worker_node_labels:
  - node-role.kubernetes.io/worker
infra_node_labels:
  - node-role.kubernetes.io/infra

rhacs_namespace: stackrox

min_access_token_max_age_seconds: 1800        # in seconds
min_access_token_inactivity_timeout: 600      # in seconds

etc_encryption_type: aesgcm

forbidden_tls_security_profile:
  - VersionTLS10
  - VersionTLS11

# routes in these namespaces has:
#   spec.tls.insecureEdgeTerminationPolicy not defined
#   spec.tls.insecureEdgeTerminationPolicy set to Allow
insecure_edge_termination_exclude_namespaces:
  - openshift-storage

acceptable_audit_profiles:
  - WriteRequestBodies
  - AllRequestBodies

garbage_collection_config:
  - evictionSoft
  - evictionHard
  - evictionSoftGracePeriod
  - imageGCLowThresholdPercent
  - imageGCHighThresholdPercent
  - evictionPressureTransitionPeriod
  - imageMinimumGCAge

project_template_objects:
  - Project
  - LimitRange
  - ResourceQuota
  - NetworkPolicy

disable_default_catalog_sources:
  - community-operators

openshift_logging_namespace: openshift-logging

allowed_registries:
  - quay.io
  - registry.redhat.io
  - registry.access.redhat.com
  - image-registry.openshift-image-registry.svc:5000

forbidden_namespaces:
  - default
  - openshift

pod_too_many_restarts: 100
...
