# ansible-playbook application-readiness.yaml --extra-vars @settings.yaml
#
---
- name: "application readiness check"
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: application readiness
      ansible.builtin.include_role:
        name: application-readiness
...
