# ansible-playbook openshift-readiness.yaml --extra-vars @settings.yaml
#
---
- name: "OpenShift cluster readiness check"
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: Verify cluster
      ansible.builtin.include_role:
        name: cluster_readiness
...
