# ansible-playbook openshift-readiness.yaml --extra-vars @settings.yaml
#
---
- name: "OpenShift: readiness check"
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: verify cluster
      ansible.builtin.include_role:
        name: cluster-readiness
...
