---
kubeconfig_file: /home/bkhoo/.kube/config

cluster_version: 4.15.8

cluster_ingress_domain: apps.cluster-12345.examle.com
ingress_ip:
  - 192.168.192.168

control_nodes: 3
worker_nodes: 3

default_storage_class: ocs-external-storagecluster-ceph-rbd

# min_access_token_max_age_seconds: 600        # playbook default
# min_access_token_inactivity_timeout: 600     # playbook default

# etc_encryption_type: aesgcm                  # playbook default

# allowed_registries:                          # playbook default
#   - quay.io
#   - registry.redhat.io
#   - registry.access.redhat.com
#   - image-registry.openshift-image-registry.svc:5000

# acceptable_audit_profiles:                   # playbook default
#   - WriteRequestBodies
#   - AllRequestBodies

# project_template_objects:                    # playbook default
#   - Project
#   - LimitRange
#   - ResourceQuota
#   - NetworkPolicy

# disable_default_catalog_sources:             # playbook default
#   - community-operators

# pod_too_many_restarts: 100                   # playbook default
...
