---
# kubeconfig_file: /home/bkhoo/.kube/config

cluster_version: 4.15.11

cluster_ingress_domain: apps.cluster-ttbng.dynamic.redhatworkshops.io
ingress_ip:
  - 150.240.143.122

control_nodes: 3
worker_nodes: 3
infra_nodes: 2

default_storage_class: ocs-external-storagecluster-ceph-rbd

# refer to roles/cluster-readiness/defaults/main.yaml for other configurable parameters
...
